### PR TITLE
Fix issue with log writing in Lambda Read-Only Environment

### PR DESCRIPTION
**Pull request by dbarrous**
This PR is to address this issue: #21 

This lambda looks for the environmental variable `LAMBDA_ENVIRONMENT` that is used by both our sorting & processing lambda function and ensures it does not import the AppDirs or attempt to write to the logger file and cause fatal file system read-only errors or missing logger file warnings in the logs.

I've tested it out and it allows the function to run successfully and sort out the files as well as preserve the original functionality in local development:
run

### CODE REVIEW

**Comment by ehsteve** [comment]
Looks like this makes it so that the hermes log file does not get created but we do want that log file to debug potential errors in the sorting code. 

We also need this problem fixed generally because for the processing lambda we will definitely want hermes logs.

**Comment by ehsteve** [comment]
So the other directories (download dir and config dir) are not used by default. The config dir is checked to see if a user config file exists if not it uses the default configrc in the package and the download dir is only meant to be used when a user downloads a file though that code does not exist right now.

**Comment by ehsteve** [comment]
How come the os changedir approach didn't work?

**Comment by dbarrous** [comment]
> Looks like this makes it so that the hermes log file does not get created but we do want that log file to debug potential errors in the sorting code.
> 
> We also need this problem fixed generally because for the processing lambda we will definitely want hermes logs.

The logs would still be generated and added to CloudWatch by the Lambda function, which then we can look at for debugging in either CloudWatch or Grafana with Loki. I could also look into trying to upload the logs of each run to an S3 bucket since the `/tmp/` folder all lambda functions use gets cleared on every run. Let me know what you think ^

**Comment by dbarrous** [comment]
> So the other directories (download dir and config dir) are not used by default. The config dir is checked to see if a user config file exists if not it uses the default configrc in the package and the download dir is only meant to be used when a user downloads a file though that code does not exist right now.

Ah ok gotcha, I was just trying to ensure It kept its original functionality outside of the Lambda Function just in case those variables were pulled anywhere else in the code.

**Comment by dbarrous** [comment]
> How come the os changedir approach didn't work?

I tried all methods of changing directory `os.chdir`, `os.system('cd /tmp/')`, I even tried creating a temporary directory and importing `hermes_core` into it to try and run my file with no luck.  It keeps breaking with the same error on this import because of the sunpy config trying to check if the directory is writable

    File "/var/task/sunpy/util/config.py", line 148, in _get_user_configdir
      if not _is_writable_dir(configdir):
    File "/var/task/sunpy/util/config.py", line 131, in _is_writable_dir
      Path(p).mkdir(parents=True, exist_ok=True)

The weirdest thing is that it does move the log to the correct folder locally (`/tmp/`) when I was testing but than when I tried it on lambda, it still broke with the same error. I then tried tweaking the config manually to see if it would work; turning `log to file` to false would also still cause the same error. 
```
[ERROR] OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
Traceback (most recent call last):
  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/var/task/lambda_function.py", line 12, in <module>
    from file_sorter.file_sorter import FileSorter
  File "/var/task/file_sorter/file_sorter.py", line 10, in <module>
    from hermes_core.util import util
  File "/var/task/hermes_core/__init__.py", line 9, in <module>
    from hermes_core.util.config import load_config, print_config
  File "/var/task/hermes_core/util/config.py", line 13, in <module>
    from sunpy.extern.appdirs import AppDirs
  File "/var/task/sunpy/__init__.py", line 55, in <module>
    config = load_config()
  File "/var/task/sunpy/util/config.py", line 33, in load_config
    config_files = _find_config_files()
  File "/var/task/sunpy/util/config.py", line 76, in _find_config_files
    config_path = Path(_get_user_configdir())
  File "/var/task/sunpy/util/config.py", line 148, in _get_user_configdir
    if not _is_writable_dir(configdir):
  File "/var/task/sunpy/util/config.py", line 131, in _is_writable_dir
    Path(p).mkdir(parents=True, exist_ok=True)
  File "/var/lang/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/var/lang/lib/python3.9/pathlib.py", line 1327, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/var/lang/lib/python3.9/pathlib.py", line 1323, in mkdir
    self._accessor.mkdir(self, mode)
```

**Comment by ehsteve** [comment]
> > Looks like this makes it so that the hermes log file does not get created but we do want that log file to debug potential errors in the sorting code.
> 
> > 
> 
> > We also need this problem fixed generally because for the processing lambda we will definitely want hermes logs.
> 
> 
> 
> The logs would still be generated and added to CloudWatch by the Lambda function, which then we can look at for debugging in either CloudWatch or Grafana with Loki. I could also look into trying to upload the logs of each run to an S3 bucket since the `/tmp/` folder all lambda functions use gets cleared on every run. Let me know what you think ^

There are two sets of logs right? Lambda creates its own set of logs but hermes_core also create a log file. 

Is there a way to add to the Aws logs? Because we could have the Hermes logger check whether it is running on Aws and just log to aws.

**Comment by dbarrous** [comment]
> There are two sets of logs right? Lambda creates its own set of logs but hermes_core also create a log file.
> 
> Is there a way to add to the Aws logs? Because we could have the Hermes logger check whether it is running on Aws and log to AWS.

So everything that is being logged in the `hermes.log` file already gets captured in the Cloudwatch Logs whenever the Lambda function is run. There would be no extra forwarding of logs necessary and this PR would fix the issue that was causing Lambda to crash. 

**Here is a `hermes.log` output of an example run:**
hermes-log-output

**Here are the Cloudwatch logs of that run:**
cloudwatch-log

**Also here is how those logs look when they are forwarded to Loki:**
logs-in-loki

**Review by ehsteve — APPROVED** [review]
This is a work around for a kind of bug in sunpy. We will work with sunpy to see if we can get this fixed but we need to have this ready by our data flow test so we should move ahead with this temporary fix.

**Pull request merged**
