### PR TITLE
CDF Data Interoperability

### PR DESCRIPTION
**Pull request by Alrobbertz**
This change adds modules and classes to enable the reading, writing, manipulation, visualization, and validation of HERMES CDF data. 

The `hermes_core.timedata.TimeData` class provides a convenient and efficient way to work with HERMES science CDF data files. The point of this class is to simplify data management, enhances data discovery, and facilitates adherence to CDF standards.

Closes:
#20 , #34 , #42 , #55

### CODE REVIEW

**Comment by ehsteve** [comment]
@Alrobbertz the dependency list needs to be updated in the pyproject file. I don't think this will solve the testing problem but it needs to be fixed regardless.

**Comment by dbarrous** [comment]
@ehsteve @Alrobbertz I fixed the errors with the missing CDF Library, the GitHub Actions, and Doc builds were using standard GitHub Action containers and needed to use our base image in order to have access to the appropriate libraries. I also went ahead and performed the linting with black and flake8 to fix those tests as well. It should be all good to go!

**Review by dbarrous — APPROVED** [review]
Looks good after the fixes applied above!

**Comment by ehsteve** [comment]
@Alrobbertz There is a lot of untested code according to coverage. Let's fix that before merging. I'd like for our coverage to be upwards of 90% generally if possible unless we have a good reason not to. Do you want to work on this together?

**Comment by tonyastrofig** [comment]
The only minor issue I have is that when I run timedata.plot(), I don't see the plot in VS code.  Does anybody know how to see it?

**Review by tonyastrofig — APPROVED** [review]
I've read all the documentation and completed both tutorials (reading_writing_data.rst and Data_Container_Demo.ipynb).  The CDF reader and writer, including manipulation and visualization of the data is in good working order and runs within the dev container.  The timedata container is easy to use and contains qualities needed, including metadata.  Signing off.

**Pull request merged**
