### PR TITLE
Generic SWxSOC Core Integration

### PR DESCRIPTION
**Pull request by Alrobbertz**
The goal of this PR is to separate all non-HERMES-specific functionality of the `hermes_core` package to a new generic multi-mission core package. This new multi-mission core package can then be used to share common functionality including CDF file writing, metadata derivations, and schema validation, with other Missions code bases. 

This was partially inspired by discussions at DASH, at the PyHC presentation, at DASH, and my own browsing of other missions that would need to use functionality similar to that in `hermes_core`. 

The main impacts are:
- I/O File Handling completely migrated to generic package
- ISTP required schema derivation and validation migrated to generic package
    - Hermes-specific schema updated here
- Data class functionality moved to generic package

### CODE REVIEW

**Comment by dbarrous** [comment]
@Alrobbertz  So I have gone ahead and tested this hermes core branch, but it seems to producing an L1 file with the name: `swxsoc_eea_l1_20000101T170901_v1.0.0.cdf` when I tested it with the recent EEA changes. Shouldn't it still be `hermes` or am I missing a piece on how it should be used?

**Review by dbarrous — APPROVED** [review]
I've tested this out and was able to generate the appropriate filename with the new refactor, looks good to me!

The only other thing to consider is the different file levels, since some missions might have different or call them different things such as `l1a` vs `l1`. But we could add this in the future as well.

**Comment by ehsteve** [comment]
Could this be tested with one of the instrument packages like `hermes_eea` before being merged? I worry that we break something for them.

**Comment by Alrobbertz** [comment]
> Could this be tested with one of the instrument packages like `hermes_eea` before being merged? I worry that we break something for them.

@Damian and I did do a test of processing EEA files with this change. I think we found a couple issues but resolved them a while ago. I can't remember if I did a another tests and compared checksums to make sure the files were _exactly_ the same. 

I think I'd like to hold off on this PR for a little while anyway while I'm working on the FITS integration. I think there will be more integration changes once the FITS schemas and validation is added to the swxsoc package.

**Pull request closed without merging**
